version: "3"
services:
  shell:
    container_name: neovim
    platform: linux/amd64
    build: .
    image: exploring-neovim
    stdin_open: true
    tty: true
    volumes:
    - ./homedir/.config:/root/.config
