#!/usr/bin/env bash

declare image="${1:-neovim-tmux-explorations-neovim}"
docker run \
    --platform linux/amd64 \
    --volume ~/work:/home/user/work \
    --volume ~/.config:/home/user/.config \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --name test \
    -i \
    -t \
    "$image"

